print(('-'*10), ' ANÁLISE DE NOMES ', ('-'*10))
nome = str(input('Qual é o seu nome? ')).strip()
print('\n')
print(('-'*10), ' ANÁLISE COMPLETA: ', ('-'*10))
print('Maiúsculas: ', nome.upper())
print('Minúsculas: ', nome.lower())
print('Quantidade de letras (sem espaço): ', len(nome) - nome.count(' '))
divisao = (nome.split())
print('Quantas letras tem o 1º nome: ', len(divisao[0]))
##print('Quantas letras tem o 1º nome: ', nome.find(' '))
